# .github/workflows/mirror.yml
name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '* 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: craigez/github-mirror-action@main
        with:
          origin: 'huggingface/peft'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REFSPACE: 'main'
